include:
  - project: devops-services
    file: jobs-bank.gitlab-ci.yml

stages:
  - build
  - deploy

build:
  stage: build
  extends: .build

deploy:
  stage: deploy
  extends: .deploy
