kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.front.name }}-route
  namespace: {{ .Values.namespace}}
spec:
  to:
    kind: Service
    name: {{ .Values.front.name }}-srv
  tls:
    termination: edge
  host: {{ .Values.front.route.host }} 
  port:
     targetPort: {{ index (index .Values.front.service.ports 0) "name" }}
